name: Synthia AI News Reporter

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:  
  push:
    branches: [master]  # or your default branch
  pull_request:
    types: [closed]


jobs:
  build:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker compose build
  
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: curl -sSf https://discord-bot-ai-trandes.onrender.com/ || echo "Ping failed"
    

  