name: Synthia AI News Reporter

on:
  workflow_dispatch:  
  push:
    branches: [master]
    tags:
      - 'v*.*.*' 
  pull_request:
    types: [closed]


jobs:
  build:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker compose build

      # - name: Run tests inside container (optional)
      #   run: docker compose run --rm app pytest || echo "Tests skipped or failed"

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker compose build
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Upload Release Asset
        run: |
          zip -r synthia-bot.zip . -x '*.git*' '__pycache__/*'
        # Upload zipped project to the GitHub release
      - name: Upload ZIP to Release
        uses: softprops/action-gh-release@v2
        with:
          files: synthia-bot.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
  
  
    

  