name: Synthia AI News Reporter

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:  # Manual run
  push:
    branches: [master]  # or your default branch
  pull_request:
    types: [closed]

concurrency:
  group: synthia-docker-group
  cancel-in-progress: true

jobs:
  build:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker compose build

  run-synthia:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run Synthia with Docker Compose
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          BOT_IMAGE_NAME: ${{ secrets.BOT_IMAGE_NAME }}
        run: |
          docker compose up --abort-on-container-exit
